development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: afly
  pool: 5
  username: root
  password: toor
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: afly_test
  pool: 5
  username: root
  password: toor
  host: localhost
producation:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: afly
  pool: 5
  username: root
  password: toor
  host: localhost